import type { Novel } from "@/types/novel";

export function generateDemoNovels(): Novel[] {
	const baseDate = new Date();

	return [
		{
			id: "1",
			title: "月光の魔法使いと星の守護者",
			description: "孤独な魔法使いと、星の力を宿した少女の物語。二人が出会った時、世界の運命が大きく動き始める。壮大なファンタジー長編。",
			userName: "星野みつき",
			aiUsed: false,
			tags: ["ファンタジー", "魔法", "冒険", "恋愛"],
			textLength: 125000,
			createDate: new Date(baseDate.getTime() - 30 * 24 * 60 * 60 * 1000).toISOString(),
			uploadDate: new Date(baseDate.getTime() - 30 * 24 * 60 * 60 * 1000).toISOString(),
		},
		{
			id: "2",
			title: "デジタルハートの恋愛方程式",
			description: "AI研究者の主人公が開発した感情を持つAIとの、現実と仮想の境界を超えた恋愛物語。",
			userName: "テクノ作家",
			aiUsed: true,
			tags: ["SF", "恋愛", "AI", "近未来"],
			textLength: 45000,
			createDate: new Date(baseDate.getTime() - 15 * 24 * 60 * 60 * 1000).toISOString(),
			uploadDate: new Date(baseDate.getTime() - 15 * 24 * 60 * 60 * 1000).toISOString(),
		},
		{
			id: "3",
			title: "猫カフェ殺人事件",
			description: "人気の猫カフェで起きた殺人事件。常連客の探偵と猫たちが謎を解く、ユーモラスなミステリー。",
			userName: "黒猫探偵",
			aiUsed: false,
			tags: ["ミステリー", "コメディ", "猫", "日常"],
			textLength: 32000,
			createDate: new Date(baseDate.getTime() - 7 * 24 * 60 * 60 * 1000).toISOString(),
			uploadDate: new Date(baseDate.getTime() - 7 * 24 * 60 * 60 * 1000).toISOString(),
		},
		{
			id: "4",
			title: "最後の桜が散る前に",
			description: "余命宣告を受けた女子高生と、彼女を支える幼馴染の切ない青春物語。春の訪れとともに紡がれる、命の輝きを描く。",
			userName: "春風さくら",
			aiUsed: false,
			tags: ["青春", "恋愛", "感動", "学園"],
			textLength: 28000,
			createDate: new Date(baseDate.getTime() - 45 * 24 * 60 * 60 * 1000).toISOString(),
			uploadDate: new Date(baseDate.getTime() - 45 * 24 * 60 * 60 * 1000).toISOString(),
		},
		{
			id: "5",
			title: "異世界転生したら最強の料理人だった件",
			description: "現代の料理人が異世界に転生し、料理の力で魔王軍と戦う!? 美味しくて強くなれる、グルメ系異世界ファンタジー。",
			userName: "グルメ冒険家",
			aiUsed: true,
			tags: ["異世界", "料理", "コメディ", "ファンタジー"],
			textLength: 89000,
			createDate: new Date(baseDate.getTime() - 20 * 24 * 60 * 60 * 1000).toISOString(),
			uploadDate: new Date(baseDate.getTime() - 20 * 24 * 60 * 60 * 1000).toISOString(),
		},
		{
			id: "6",
			title: "雨の日の約束",
			description: "梅雨の季節、傘を忘れた日に出会った二人。雨の日だけの特別な関係が、やがて...",
			userName: "雨音詩人",
			aiUsed: false,
			tags: ["恋愛", "短編", "日常", "梅雨"],
			textLength: 8500,
			createDate: new Date(baseDate.getTime() - 3 * 24 * 60 * 60 * 1000).toISOString(),
			uploadDate: new Date(baseDate.getTime() - 3 * 24 * 60 * 60 * 1000).toISOString(),
		},
		{
			id: "7",
			title: "深海都市アトランティア",
			description: "地球温暖化により海面下に沈んだ都市で生きる人々。深海の闇に隠された真実とは。",
			userName: "海洋SF作家",
			aiUsed: false,
			tags: ["SF", "ディストピア", "環境", "サスペンス"],
			textLength: 67000,
			createDate: new Date(baseDate.getTime() - 60 * 24 * 60 * 60 * 1000).toISOString(),
			uploadDate: new Date(baseDate.getTime() - 60 * 24 * 60 * 60 * 1000).toISOString(),
		},
		{
			id: "8",
			title: "魔王の娘はパン屋さん",
			description: "魔王の娘として生まれたが、パン作りが大好きな主人公。人間界でパン屋を開く、ほのぼのファンタジー。",
			userName: "パン工房",
			aiUsed: true,
			tags: ["ファンタジー", "日常", "料理", "ほのぼの"],
			textLength: 42000,
			createDate: new Date(baseDate.getTime() - 25 * 24 * 60 * 60 * 1000).toISOString(),
			uploadDate: new Date(baseDate.getTime() - 25 * 24 * 60 * 60 * 1000).toISOString(),
		},
		{
			id: "9",
			title: "時を超える手紙",
			description: "古い屋敷で見つけた100年前の手紙。それに返事を書いたら、過去の人と文通が始まった。時空を超えた恋の物語。",
			userName: "時の旅人",
			aiUsed: false,
			tags: ["恋愛", "タイムトラベル", "手紙", "歴史"],
			textLength: 55000,
			createDate: new Date(baseDate.getTime() - 10 * 24 * 60 * 60 * 1000).toISOString(),
			uploadDate: new Date(baseDate.getTime() - 10 * 24 * 60 * 60 * 1000).toISOString(),
		},
		{
			id: "10",
			title: "僕と彼女と夏祭り",
			description: "高校最後の夏、幼馴染との関係に変化が。花火大会の夜に起きた出来事とは。",
			userName: "夏風",
			aiUsed: false,
			tags: ["青春", "恋愛", "学園", "夏"],
			textLength: 15000,
			createDate: new Date(baseDate.getTime() - 5 * 24 * 60 * 60 * 1000).toISOString(),
			uploadDate: new Date(baseDate.getTime() - 5 * 24 * 60 * 60 * 1000).toISOString(),
		},
		{
			id: "11",
			title: "宇宙ステーションの密室",
			description: "宇宙ステーションで起きた殺人事件。重力のない密室での犯行トリックとは？",
			userName: "宇宙探偵",
			aiUsed: true,
			tags: ["ミステリー", "SF", "宇宙", "密室"],
			textLength: 38000,
			createDate: new Date(baseDate.getTime() - 35 * 24 * 60 * 60 * 1000).toISOString(),
			uploadDate: new Date(baseDate.getTime() - 35 * 24 * 60 * 60 * 1000).toISOString(),
		},
		{
			id: "12",
			title: "竜と共に生きる村",
			description: "人間と竜が共存する小さな村。竜使いの少年と、都会から来た少女の冒険譚。",
			userName: "竜の語り部",
			aiUsed: false,
			tags: ["ファンタジー", "冒険", "竜", "友情"],
			textLength: 72000,
			createDate: new Date(baseDate.getTime() - 40 * 24 * 60 * 60 * 1000).toISOString(),
			uploadDate: new Date(baseDate.getTime() - 40 * 24 * 60 * 60 * 1000).toISOString(),
		},
	];
}