// テスト用の共通データ
export const createMinimalNovelData = (
	overrides: Record<string, unknown> = {},
) => ({
	id: "123",
	title: "テスト小説",
	genre: "0",
	xRestrict: 0,
	restrict: 0,
	url: "https://example.com/novel.jpg",
	tags: ["タグ1", "タグ2"],
	userId: "456",
	userName: "テスト作者",
	profileImageUrl: "https://example.com/profile.png",
	textCount: 1000,
	wordCount: 500,
	readingTime: 120,
	useWordCount: false,
	description: "テスト説明",
	isBookmarkable: true,
	bookmarkData: null,
	bookmarkCount: 10,
	isOriginal: false,
	marker: null,
	titleCaptionTranslation: {
		workTitle: null,
		workCaption: null,
	},
	createDate: "2024-01-01T00:00:00+09:00",
	updateDate: "2024-01-01T00:00:00+09:00",
	isMasked: false,
	aiType: 0,
	isUnlisted: false,
	...overrides,
});
